#!/bin/bash

# msk-qdess
#
# @brief: Run DESS analysis on patient folder specified as an argument
#           1. Calculate t2 map
#           2.
#
# @usage (from terminal/command line):
#   ./msk-qdess PATH_TO_PATIENT_FOLDER qDESS_DICOM_FOLDER_NAME
#   eg: "./msk-qdess subject_scans/patient01 001"
#
# @initialization protocol:
#   1. run "chmod +x msk-qdess" from the command line
#   2. Update `WEIGHTS_DIRECTORY` field below
#
# @author: Arjun Desai, Stanford University
#          (c) Stanford University, 2018

WEIGHTS_DIRECTORY=""
if [ -z "$WEIGHTS_DIRECTORY" ]; then
    echo "Please define WEIGHTS_DIRECTORY in script. Use the absolute path"
    exit 125
fi

if [ $# -eq 1 ]
then
SERIES="qdess"
else
SERIES=$2
fi

# find relevant dicom files

FILES=$(find $1 -type d -name $SERIES)

cd ..

for i in $FILES; do
    DIRNAME=$(dirname $i)
    DIRNAME="$DIRNAME/data"
    python -m pipeline -d $i -s $DIRNAME qdess -t2 -fc segment -rms --weights_dir $WEIGHTS_DIRECTORY
    python -m pipeline -l $DIRNAME knee
done
