#!/bin/bash

echo "This file is currently deprecated - if needed, please make an issue on the corresponding Github repository"
exit 125

WEIGHTS_DIRECTORY="/Users/arjundesai/Documents/stanford/research/msk_pipeline_raw/weights"
if [ -z "$WEIGHTS_DIRECTORY" ]; then
    echo "Please define WEIGHTS_DIRECTORY in script. Use the absolute path"
    exit 125
fi

if [ $# -eq 1 ]
then
SERIES="qdess"
else
SERIES=$2
fi

# find relevant dicom files

FILES=$(find $1 -type d -name $SERIES)

cd ..

for i in $FILES; do
    DIRNAME=$(dirname $i)
    SAVE_DIRNAME="$DIRNAME/data"
    CUBEQUANT_DIRNAME="$DIRNAME/cubequant"
    CONES_DIRNAME="$DIRNAME/cones"
    TARGET_SCAN="$SAVE_DIRNAME/qdess_data/echo1.nii.gz"
    MASK="$SAVE_DIRNAME/fc/fc.nii.gz"

    CUBEQUANT_INTERREGISTERED_DATA="$SAVE_DIRNAME/cubequant_data/interregistered"
    CUEQUANT_T1RHO="$SAVE_DIRNAME/cubequant_data/t1_rho.nii.gz"


    CONES_INTERREGISTERED_DATA="$SAVE_DIRNAME/cones_data/interregistered"
    CONES_T2STAR="$SAVE_DIRNAME/cones_data/t2_star.nii.gz"

    echo ""
    echo "----------Analyzing $DIRNAME---------"

    # use qDESS to get femoral cartilage segmentation + 3D t2 maps
    echo "qDESS T2map time:"
    python -m pipeline -d $i -s $SAVE_DIRNAME qdess -fc -t2

   	echo "segmentation time:"
    python -m pipeline -l $SAVE_DIRNAME -s $SAVE_DIRNAME qdess -fc segment -rms --weights_dir $WEIGHTS_DIRECTORY

    echo "cubequant registration time:"
	echo $CUBEQUANT_INTERREGISTERED_DATA
    python -m pipeline -d $CUBEQUANT_DIRNAME -s $SAVE_DIRNAME cq interregister -ts $TARGET_SCAN

    echo "cubequant T2map time:"
    python -m pipeline -l $SAVE_DIRNAME cq -t1rho -fm $MASK

    echo "cones registration time:"
    python -m pipeline -d $CONES_DIRNAME -s $SAVE_DIRNAME cones interregister -ts $TARGET_SCAN

    echo "cones t2star time:"
    python -m pipeline -l $SAVE_DIRNAME cones -t2star -fm $MASK

    echo "analysis time"
    python -m pipeline -l $SAVE_DIRNAME knee -fc -t2 -t1_rho -t2_star
done
